spring:
  datasource:
    url: jdbc:postgresql://localhost:${EXTERNAL_DB_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # or validate, update, create
    properties:
      hibernate:
        default_schema: public